version: '3.9'

services:
  
  # docker run -v %cd%:/app -v /app/node_modules --env PORT=5000 -p 3000:5000 -d --name nodejs-babel-container sample-nodejs-project:latest
  sample_project_build_run_container: 
    build:
      context: .
      dockerfile: dockerfile
    image: sample-nodejs-project:latest
    container_name: sample_project_build_run_container
    ports:
      - 3000:5000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=5000

  # docker run -v %cd%:/app -v /app/node_modules --env-file ./.env -p 3000:5000 -d --name nodejs-babel-container sample-nodejs-project:latest
  sample_project_run_container: 
    image: sample-nodejs-project:latest
    container_name: sample_project_run_container
    ports:
      - 3000:5000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env