FROM node:16
WORKDIR /app
# below line is the relative path for /app as .
COPY package.json .
RUN npm install
# below line is the relative path for first "." is the current project path AND second "./" is the container WORKDIR path.
COPY . ./
ENV PORT 3000
EXPOSE $PORT
CMD [ "npm", "run", "start:prod" ]