# FROM node:16
ARG NODE_VERSION
FROM node:$NODE_VERSION

WORKDIR /app

# below line is the relative path for /app as .
COPY package.json .

# RUN npm install
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ] || [ "$NODE_ENV" = "local" ] ; then npm install ; else npm install --omit=dev ; fi

# below line is the relative path for first "." is the current project path AND second "./" is the container WORKDIR path.
COPY . ./
ENV PORT 3000
EXPOSE $PORT
CMD [ "npm", "run", "start:prod" ]