version: '3.9'

services:
  
  # docker build --pull --rm -f "dockerfile" -t sample-nodejs-project:latest "."
  # docker run -v sample_project_dev_volume:/app -v sample_project_dev_volume:/app/node_modules --env NODE_ENV=development --env PORT=5000 -p 3000:5000 -d --name nodejs-babel-container sample-nodejs-project:latest
  sample_project_build_run_container: 
    build:
      context: .
      dockerfile: dockerfile
    image: sample-nodejs-project:latest
    container_name: sample_project_build_run_container
    ports:
      - 3000:5000
    volumes:
      - sample_project_dev_volume:/app
      - sample_project_dev_volume:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: npm run start:dev

  # docker run -v sample_project_dev_volume:/app -v sample_project_dev_volume:/app/node_modules --env NODE_ENV=development --env PORT=5000 -p 3000:5000 -d --name nodejs-babel-container sample-nodejs-project:latest
  sample_project_build_env_run_container: 
    image: sample-nodejs-project:latest
    container_name: sample_project_build_env_run_container
    ports:
      - 3000:5000
    volumes:
      - sample_project_dev_volume:/app
      - sample_project_dev_volume:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: npm run start:dev

  # docker run -v sample_project_dev_volume:/app -v sample_project_dev_volume:/app/node_modules --env NODE_ENV=development --env-file ./.env -p 3000:5000 -d --name nodejs-babel-container sample-nodejs-project:latest
  sample_project_env_file_run_container: 
    image: sample-nodejs-project:latest
    container_name: sample_project_env_file_run_container
    ports:
      - 3000:5000
    volumes:
      - sample_project_dev_volume:/app
      - sample_project_dev_volume:/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: npm run start:dev

volumes:
  sample_project_dev_volume:
